"use client";
import {useEffect,useState} from "react";
import PuckBuilder from "./puck-builder";

const nav=[["Tổng quan","", "core"],["Visual Page Builder","builder","core"],["Trang","pages","content"],["Sites","sites","content"],["Sản phẩm","products","commerce"],["Danh mục","categories","commerce"],["Công trình","projects","content"],["Bài viết SEO","articles","content"],["Media Library","media","content"],["SEO & Redirects","seo","growth"],["Navigation","navigation","growth"],["Versions","revisions","system"],["Deployments","deployments","system"],["Người dùng & RBAC","users","system"],["Cài đặt","settings","system"],["Tài khoản","account","system"]];
const legacy={products:"products",categories:"categories",articles:"articles",media:"media",revisions:"revisions",settings:"settings",account:"account"};
const titles={builder:"Visual Page Builder",pages:"Pages",sites:"Sites",products:"Products",categories:"Categories",projects:"Projects",articles:"SEO Articles",media:"Media Library",seo:"SEO & Redirects",navigation:"Navigation",revisions:"Versions & Revisions",deployments:"Deployments",users:"Users & RBAC",settings:"Site Settings",account:"Account"};

function Login({onOk}){const [busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:fd.get("username"),password:fd.get("password")})});let j={};try{j=await r.json()}catch{}if(!r.ok){setError(j.error||"Không đăng nhập được.");setBusy(false);return}onOk()}return <div className="login-wrap"><section className="login-art"><div><div className="eyebrow" style={{color:"#dfb46e"}}>Đại Long Digital Studio</div><h1>Quản trị website như một hệ thống xuất bản thực thụ.</h1><p>Chỉnh nội dung, sản phẩm, hình ảnh, SEO, phiên bản và preview trong một workspace riêng.</p></div><div className="muted" style={{color:"#d5e3f5"}}>admin.gomsudailong.vn · Internal CMS</div></section><section className="login-panel"><form className="login-box" onSubmit={submit}><div className="eyebrow">Khu vực nội bộ</div><h2>Đăng nhập CMS</h2><p className="muted">Dùng tài khoản quản trị để tiếp tục.</p><div className="field"><label>Tài khoản</label><input name="username" autoComplete="username" required/></div><div className="field"><label>Mật khẩu</label><input name="password" type="password" autoComplete="current-password" required/></div>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?"Đang kiểm tra…":"Đăng nhập quản trị"}</button></form></section></div>}

function Sidebar({active}){const groups=[["core","Workspace"],["content","Nội dung"],["commerce","Thương mại"],["growth","Tăng trưởng"],["system","Hệ thống"]];return <aside className="sidebar"><div className="brand"><div className="mark">DL</div><div><strong>Đại Long CMS</strong><span>Publishing workspace</span></div></div>{groups.map(([g,label])=><div className="group" key={g}><div className="group-title">{label}</div><nav className="nav">{nav.filter(x=>x[2]===g).map(([name,slug])=><a className={(active===slug?"active ":"")+(["pages","sites","projects","seo","navigation","deployments","users"].includes(slug)?"soon":"")} href={"/admin"+(slug?"/"+slug:"")} key={slug||"home"}>{name}</a>)}</nav></div>)}</aside>}

function Dashboard(){const mods=[["Visual Page Builder","Puck kéo/thả, draft, version và publish record.","builder","Puck"],["Products & Categories","Giữ kết nối dữ liệu production hiện tại.","products","Sẵn sàng"],["Media Library","Upload và quản lý asset.","media","Sẵn sàng"],["SEO Articles","Soạn, draft, publish.","articles","Sẵn sàng"],["Pages & Sites","Schema trang và multi-site.","pages","Supabase"],["SEO & Redirects","Metadata, sitemap, canonical, redirects.","seo","Supabase"],["Versions","Snapshot và restore.","revisions","Supabase + legacy"],["Deployments","Publish pipeline Vercel.","deployments","Tiếp theo"]];return <div><div className="hero"><div><div className="eyebrow">Publishing workspace</div><h1>Dashboard</h1><p className="muted">Một nơi để quản lý toàn bộ nội dung website Đại Long.</p></div><div className="pill">Production connected</div></div><div className="grid stats"><div className="card stat"><b>1</b><span>Website production</span></div><div className="card stat"><b>9</b><span>Module / shell</span></div><div className="card stat"><b>0</b><span>Runtime error gần nhất</span></div><div className="card stat"><b>v0.4.1</b><span>Puck + CMS schema</span></div></div><div className="grid modules">{mods.map(([t,d,s,status])=><a className="card module" href={"/admin/"+s} key={s}><h3>{t}</h3><p>{d}</p><span className="tag">{status}</span></a>)}</div></div>}

function Placeholder({slug}){return <div><div className="hero"><div><div className="eyebrow">Module architecture</div><h1>{titles[slug]}</h1><p className="muted">Route đã tách riêng. Dữ liệu mới sử dụng CMS API server-side và schema Supabase.</p></div></div><div className="card"><div className="notice"><b>Không tạo dữ liệu giả.</b><br/>UI CRUD đầy đủ sẽ bật sau khi migration và Vercel env của Supabase được áp dụng.</div><div className="status-row"><span className="status">Route ready</span><span className="status">Schema ready</span><span className="status warn">Env / migration check</span></div></div></div>}

function Legacy({slug}){return <div><div className="hero"><div><div className="eyebrow">Connected module</div><h1>{titles[slug]}</h1><p className="muted">Module cũ vẫn được giữ để dữ liệu production không bị gián đoạn trong lúc migration.</p></div><a className="ghost" href={"/legacy/admin/"+legacy[slug]} target="_blank">Mở toàn màn hình ↗</a></div><div className="card frame-card"><iframe className="frame" title={titles[slug]} src={"/legacy/admin/"+legacy[slug]}/></div></div>}

export default function AdminClient({path}){const slug=path[0]||"";const [auth,setAuth]=useState("checking");useEffect(()=>{fetch("/api/admin/settings",{cache:"no-store"}).then(r=>setAuth(r.status===401?"out":"in")).catch(()=>setAuth("out"))},[]);const title=slug?titles[slug]:"Dashboard";if(auth==="checking")return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",color:"#667085"}}>Đang kết nối CMS…</div>;if(auth==="out")return <Login onOk={()=>setAuth("in")}/>;return <div className="app"><Sidebar active={slug}/><main className="main"><header className="topbar"><div className="title">{title}</div><span className="pill">gomsudailong.vn</span><div className="spacer"/><a className="ghost" href="https://gomsudailong.vn" target="_blank">Xem website ↗</a><button className="ghost" onClick={async()=>{await fetch("/api/admin/logout",{method:"POST"});setAuth("out")}}>Đăng xuất</button></header><section className={"content "+(slug==="builder"?"builder-mode":"")}>{!slug?<Dashboard/>:slug==="builder"?<PuckBuilder/>:legacy[slug]?<Legacy slug={slug}/>:<Placeholder slug={slug}/>}</section></main></div>}
